{{- if and (.Values.e2eTestJob.enabled) (.Values.e2eTestJob.createSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: e2e-secret
type: Opaque
stringData:
  GITHUB_ACTION_REF: "{{ .Values.e2eTestJob.ref }}"
  GITHUB_API_URL: "{{ .Values.e2eTestJob.env.githubApiUrl }}"
  GITHUB_TOKEN: "{{ .Values.e2eTestJob.env.githubToken }}"
{{- end }}
