{{- if eq .Values.imageTag "latest" }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  lookupPolicy:
    local: false
  {{- if not .Values.development}}
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: {{ .Values.imageName }}:{{ .Values.imageTag }}
    importPolicy:
      scheduled: true
    name: {{ .Values.imageTag }}
    referencePolicy:
      type: Source
  {{- end}}
{{- end }}
