apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  ports:
    - name: "{{ .Values.servicePort }}-tcp"
      port: {{ .Values.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.servicePort }}
  selector:
    app: {{ .Values.name }}
    deploymentconfig: {{ .Values.name }}
  sessionAffinity: None
  type: ClusterIP