---
ci_cd_namespace: omp-ci-cd
dev_namespace: omp-dev
test_namespace: omp-test
app_name: omp-frontend

build_vars:
  NAME: '{{ app_name }}'
  OUTPUT_IMAGE_NAME: '{{ app_name }}'
  OUTPUT_IMAGE_TAG: latest
  PUSH_SECRET: quay-registry-secret
  GIT_URL: https://github.com/rht-labs/open-management-portal-frontend.git
  GIT_REF: master

pipeline_vars:
  PIPELINE_SOURCE_REPOSITORY_URL: https://github.com/rht-labs/open-management-portal-frontend.git
  PIPELINE_SOURCE_REPOSITORY_REF: master
  NAME: '{{ app_name }}'

dev_vars:
  NAME: '{{ app_name }}'
  IMAGE_NAME: '{{ app_name }}'
  IMAGE_TAG: latest
  BASE_URL: https://[my-application-url].com/
  BACKEND_URL: https://[my-application-backend-url].com/
  CLIENT_ID: open-management-portal
  AUTHORIZATION_ENDPOINT: https://[my-sso-url].com/auth/realms/omp/protocol/openid-connect/auth
  USERINFO_ENDPOINT: https://[my-sso-url].com/auth/realms/omp/protocol/openid-connect/userinfo
  TOKEN_ENDPOINT: https://[my-sso-url].com/auth/realms/omp/protocol/openid-connect/token
  END_SESSION_ENDPOINT: https://[my-sso-url].com/auth/realms/omp/protocol/openid-connect/logout
  REACT_APP_BACKEND_URI: https://omp-backend-omp-dev.apps.s11.core.rht-labs.com

test_vars:
  NAME: '{{ app_name }}'
  IMAGE_NAME: '{{ app_name }}'
  IMAGE_TAG: latest
  BASE_URL: https://[my-application-url].com/
  BACKEND_URL: https://[my-application-backend-url].com/
  CLIENT_ID: open-management-portal
  AUTHORIZATION_ENDPOINT: https://[my-sso-url].com/auth/realms/omp/protocol/openid-connect/auth
  USERINFO_ENDPOINT: https://[my-sso-url].com/auth/realms/omp/protocol/openid-connect/userinfo
  TOKEN_ENDPOINT: https://[my-sso-url].com/auth/realms/omp/protocol/openid-connect/token
  END_SESSION_ENDPOINT: https://[my-sso-url].com/auth/realms/omp/protocol/openid-connect/logout
  REACT_APP_BACKEND_URI: https://omp-backend-omp-test.apps.s11.core.rht-labs.com

openshift_cluster_content:
- object: '{{ app_name }}'
  content:
  - name: pipeline
    template: 'https://raw.githubusercontent.com/redhat-cop/openshift-templates/v1.4.15/jenkins-pipelines/jenkins-pipeline-template-with-ocp-triggers.yml'
    params_from_vars: '{{ pipeline_vars }}'
    namespace: '{{ ci_cd_namespace }}'
    tags: 
    - pipeline
  - name: build
    template: '{{ inventory_dir }}/../templates/build.yml'
    params_from_vars: '{{ build_vars }}'
    tags:
      - build
  - name: deployment
    template: '{{ inventory_dir }}/../templates/deploy.yml'
    params_from_vars: '{{ dev_vars }}'
    namespace: '{{ dev_namespace }}'
    tags:
      - deploy
      - dev
  - name: deployment
    template: '{{ inventory_dir }}/../templates/deploy.yml'
    params_from_vars: '{{ test_vars }}'
    namespace: '{{ test_namespace }}'
    tags:
      - deploy
      - test