export const initialState = {
  customer_name: null,
  project_name: null,
  description: null,
  location: null,
  start_date: null,
  end_date: null,
  archive_date: null,
  engagement_users: [],
  engagement_lead_name: null,
  engagement_lead_email: null,
  technical_lead_name: null,
  technical_lead_email: null,
  customer_contact_name: null,
  customer_contact_email: null,
  ocp_cloud_provider_name: null,
  ocp_cloud_provider_region: null,
  ocp_version: null,
  ocp_sub_domain: null,
  ocp_persistent_storage_size: null,
  ocp_cluster_size: null,
  engagement: null,
};
