apiVersion: v1
kind: Template
metadata:
  name: "${NAME}"
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: "${OUTPUT_IMAGE_NAME}"
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: '${NAME}'
    name: '${NAME}'
  spec:
    nodeSelector:
    output:
      to:
        kind: ImageStreamTag
        name: '${NAME}:${BUILD_TAG}'
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
  status:
    lastVersion: 1
parameters:
- name: NAME
  description: The name of the resources to be created
  required: true
- name: OUTPUT_IMAGE_NAME
  description: The imagestream to push the image to when it has been built
  required: true
- name: OUTPUT_IMAGE_TAG
  description: The tag to give the image when it has been built
  required: true
- name: GIT_URL
  description: The Git URL of the project containing the OMP frontend
  required: true
- name: GIT_REF
  description: The git reference to pull for building the app
  required: true